### ISSUE TITLE
Trim error

### ISSUE THREAD

**Issue by bluetechy** [Unicity/Gauntlet#18]
@powerc9000 I am now getting the following error:

````
/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/test_runner.js:214
        if(actual.trim() === expected.trim()){
                 ^
TypeError: Cannot read property 'trim' of undefined
    at Request._callback (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/test_runner.js:214:18)
    at Request.self.callback (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
````

**Comment by bluetechy** [comment]
Error now seems to be resolved as of: https://github.com/Unicity/Gauntlet/commit/94acb505ec8ba7d0e4917687793b23b10e945d83
