### ISSUE TITLE
Handling cases where there is no input file

### ISSUE THREAD

**Issue by bluetechy** [Unicity/Gauntlet#8]
@powerc9000 How do I handle cases where there is no input file?  For example:

````
	"service%3DGetCountries%2FHydra-API": {
		"name": "service=GetCountries/Hydra-API",
		"endpoint": "service=GetCountries/Hydra-API",
		"gist": "",
		"inputs": {
			"t1": ""
		},
		"outputs": {
			"t1": "output.json"
		}
	},
````

Right now, I am getting the following error:

````
fs.js:603
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at /home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/test_runner.js:109:34
    at Array.forEach (native)
    at /home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/test_runner.js:66:17
    at Array.forEach (native)
    at Object.main (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/test_runner.js:48:9)
    at Object.<anonymous> (/home/travis/.nvm/versions/node/v4.1.2/lib/node_modules/unicity_gauntlet/gauntlet:95:13)
    at Module._compile (module.js:434:26)
````

**Comment by bluetechy** [comment]
@powerc9000 I can envision three possible representations:

````
"inputs": {
    "t1": ""
},
````
or

````
"inputs": {
    "t1": null
},
````
or

````
"inputs": {
},
````

Which is the preferred representation? Or, is it possible to handle all three cases?

**Comment by powerc9000** [comment]
I think `null` will be the preferred way, but I can make it handle all 3.
